Resources:
  SecretsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:provider.environment.SECRETS_TABLE}
      AttributeDefinitions:
        - AttributeName: secretId
          AttributeType: S
        - AttributeName: linkId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: creationTime
          AttributeType: N
      KeySchema:
        - AttributeName: secretId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expirationTime
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.LINK_ID_INDEX}
          KeySchema:
            - AttributeName: linkId
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - ciphertext
            ProjectionType: INCLUDE
        - IndexName: ${self:provider.environment.USER_ID_INDEX}
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: creationTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
